sudo: false
language: node_js
node_js:
  - '12'
  - '14'
before_script: make travis-init
script: make travis
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./tools/publish.sh
    on:
      branch: master
      node_js: 12
env:
  global:
    - secure: BcQciZL1in+UQzoEClOxSJNdNS3uoJlChtIu7BsHZXTjuawXWZXWvkNgytxZ0Yxm+Oifgvc+GAf69ar7fbpHSuEnAGph4auwoJP1OMGHQpo8aFoZ7ItBbLkztxDSExim3/6NuSpuefcxhZsAdK+I1XYNA5esFc1KikeNWTqqDYH8fxTWCNIL3Cd+eWkiUiq9xbCuPg6ucWNsDEW6Gu2H101l6k7t6oJqQ85xcIJxt1EPh7G+W6s0xPLprZBGJPc/8TsX1ub91Htgrd+wmtWcyY5eCyoNiq25MgpvYFmvjY9f8C5RB+LqdCrGilqXFunOTZm/uMTIXdkuIidmvfb/aLNjAj4sKMW4zQt2l55l66+UYYKXjbRBT/mHXvssuWu6TIEFR2xWIb00dfV9qqpImU0Ecv098XyC1NNfp2BDkEyqwv6+ZkYI7fgRJ8sOmLEiZ/f+cDqqdQwX0EKL0BjpHhb8OoX4JaqaiDB6uwOVOgeURYJwEzJrnxXV8nqhvPp6p04YOp11DAOoUigGMu+MUlu8MXKjf0yFibu69O6dEtV+oYkPCbQnigENStbtIewPrk67LJWK2PNNtlUg0bgmAM1ptL7Rc/XjOwMmOC2oouevJ4cAG779qz1PlyuSBDDwEUddoYAJl64Fc7FPtGd3qj1JKLX7LSNDE9c8H3I17Vc=
    - secure: e5CWTA/xrwRNlY997RddW00YL+Ya5zHVgPQuIUcIBXT5GbU8ox+WSqFrzdYwtmQCMUU74dC3lhDq4WHW1kQ0yt3Wr3JpApzUbJDeLQMKlUdvBfxKJ0EyvKSZYXlVpgAEt0dv434WU52SyCAzpj8CENTsLsoaFeSt46r7LVvt3ZiS6gcCoCkdqz3ewE99d0DQ6V8GD7O1Usfl2A8MfwVEPMiqD9Jl07/pRyDP56YojA/UHCR2dRUU/Mf6VdR8TSbo2iobNdXo95sfkfXuLTgLHhDDHss/pWhi2T7QRnPOlYu/v/chY/7mMTP8CLIkUqSkRBAwQIH6PZavt8WYQvxujS0PXPYrueRcyFnpEUg80oD2PNRLysKa7ZczLjNDt89+GCbvJzuwx0ZBiW3t7LzcbuCAnCnaqvIMsBbqkwmYOYpxvOpx4U+EgZs5xn8WQzg2nf3kvCCh9JVXQFAs5IKv9baXWyWeN0UIORyL1qIpH5zGXl7HlqP2IlEN2CD7Iknq9bskCTh6mjl5PMClY3YDEnGlLDquwQ3X3hQWlysQOZmebQyjxfXxQN9CUVOTjTRjs3cmlzg9iCJAMdW0L1hHlT+QJhwwkhUyjaOeoQXFyWXngjfzsVp4GIQf+qIVqslLi+dZ5xs0SfNX8kUFQ1rXvUffF1cXlcXqjZLBPMAA/U0=
    - secure: D0TNV13beYXXbSESXn50LroG9JjErGk9Hku09zh7WO2AOZ8zM6KnJDYLjWPAEwEwFzYTWcHUKbGLXhDXlBIQb4l5ODoi7doC/Xfjr9dLsrMiaxKsRUkxiTM0ne/PsHSJ5E8zydP5ViBPuw3jJuu7h/qkvqdiLsLSIMcVZI8aktZBEiKRMvbeUBZwsJ+agvhnhNkpRexQL8hkfuk+B01EQsbHF3xzNN8Z+xzTF5beCUUYQn1RczEl/oUEasl48cpQPjWwuVQK6VWVLnf0Ou43YXc1kZddxl3m7AlhYaKgr5Z9JjIPWZ0qW4d/91g6nQX2ErlyV4fpj/78PcNChpxGMDbd5qLErYu83cyPdEINpjfMz4dORDFP3ykffh5rl/QNsZ7kLopfZ18prIzFyxxC3t8XEGjf4juJnwZeZtDXXcquGi+HrsQvK53g2CwmBnLesBIKBd3QXyWwPeP6CO+07lyBtM8FX3sitMfariAda3hIDFgUSAA7RLvJosCq6v8L+QlE4c0vhleHSZ+NQwCop7R+eu8+ZFA/SQZsovgWG8NkCAiTBvk53aoLNJShM94oreg7+iPILDGxveHJm47r2wpsNTUXAczbfJywo8ekaQrM0cWTYXR/IbdKrtYCzV7U7/FuTUriJa9oLoW9KfUVRHh+Ggmm8VcBta0frW+cnIQ=
