sudo: false
language: node_js
node_js:
- '12'
- '14'
before_script: make travis-init
script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./tools/publish.sh
  on:
    branch: master
    node_js: 12
env:
  global:
  - secure: bYjHdnzPQER7kH8NyBsNB+Pz6J5mqE2g5WhJQ502VKCz8097s9V4fW77cd+p3X7FNqjnCBS91nPMNmTOaXzyUrjMkgTATBlna3ig+uTO1dOMLgbF8evux8fRE1+UAIckZgzomVJ5LE7TmyQpOBHYVU2sa7eyQcapLHC2HTHj5vwllHh2irzBhKQGDpahKudVnCBnDPxHLs011lD9w/65YKW+O36vNS0/ThmX0kf/WkNf9PQmuDvc8fZFZAfV0lEsPmW2Noha1fh8nzhFAeoCr+eC6TK0L9yVZKAMlDnXwd4QPs0u7+xn59duqZd0MJGdQqsXF1GmYmMHl93CPeSZj2AJKijUUpuqxBNerpkpJ+sSTkaqmtvObg0swh3Ijglr0W0aKgFFojS2uUWjVIDb0KEVP9QsHzcMdqQDA5khkw4x0B4AoPsJfCTBiyepmr/Z6+2AEGFfv0jatlgXZMjlvg6gE+xsjkH/lU9vSiH5ER6xsxVNB8mLI3KlWFpz6u67YNMBT7mGOGDcyzQb3o0F6/j7TZNk0qNyXIDcm7kMmVrS9kBSOV7U9vRdrEA0RtekkY+G+V7YFJoctMrzzTG+eyEOGGXqTDRsFzg+wZBvKJJMy+e0CI6jULz8jrjtXQNvJnl4JIu1aUwIGAHMxB3Pw5Hnpjk2ZjqiSHbnhBwuSJc=
  - secure: rSsSOqNselStnAivYzrvFGyrGwfu9J8NnCv9NzL89f3OleeY27MnkWHtbvfyR0SQDkmzs+tqSf6daDmZH/sQA8nTgzClyccGZIDx/xtdMQdEnrqua6HTRF6AqqbeBDiF05y0gBh37gB6/PxGCnqy19to/kKmCasWXqayJsVGIvaXyEYRdOCqojW+KfmYqgxvNgK9s3Yss9Fb/XUaAvJixEcPceS9gvN/hGSRQFYhB7n4z2XZVJr/ZT59noGewhpFb51vAU+yDrXEuHvNFibLenje3ji0lhfUEykN/ecdLNaYLpJV8AvylTuImbBKTIsyFC+mhDmZHSTC8azF4qZ3SCUoqRKjPAf34tb6NwfXX0Ugm49Fc0US9obdi61xPiq18OwTaLrsva56CfQcYRqN9gef8WvX5UOUz7VtMTKzVFR8zME0zanfktWHmuYGHWmq6pd5yZu6RFlwP0FP328RuCeN3dm826JOeEyS/jUych0rhRL/3OhsW8FNoZBy9iaGyRX/3TRUUs0F2FGiQXGEdjGqc5oWOepYlNgU4Tbp6Fn8svhlsRz719xknqhIdCIBBJbOEGiC1ibV70GePGBR2JUEy5owxJ4G1tw7qKBIM6hLrJOG1NyMyPT8ztTYMn33EUXKL5+IfTBrVmlyvCVKENSi8Og7Vk1t3nLcNMqoB+M=
