/* eslint-disable max-len */
/* eslint-disable array-callback-return */
/* eslint-disable consistent-return */
/* eslint-disable import/no-dynamic-require */
/* eslint-disable global-require */
/* eslint-disable no-console */
const fs = require('fs');
const path = require('path');

const { getPackages } = require('./util');

const packageList = getPackages({ publicOnly: true }).map(
  (x) =>
    `- [${x.name} <img src="https://img.shields.io/npm/v/${x.name}.svg" alt="Version">](https://www.npmjs.com/package/${x.name})`
);

const readmeFile = path.join(__dirname, '../README.md');
const readmeContent = `![abt-node](https://www.arcblock.io/.netlify/functions/badge?text=ABT%20Node)

## Table of Contents

- [Table of Contents](#Table-of-Contents)
- [Introduction](#Introduction)
- [Packages](#Packages)
- [License](#License)

## Introduction

[![lerna](https://img.shields.io/badge/maintained%20with-lerna-cc00ff.svg)](https://lernajs.io/)
[![docs](https://img.shields.io/badge/powered%20by-arcblock-green.svg)](https://docs.arcblock.io)
[![Gitter](https://badges.gitter.im/ArcBlock/community.svg)](https://gitter.im/ArcBlock/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

> Last updated at ${new Date().toLocaleString()}

This repo contains ABT Node Daemon and core blocklets.

## Getting Started

Checkout instructions [here](./docs/contribute.md) on how to contribute.

## Packages

${packageList.join('\n')}

## Run in Docker

You can use ABT Node with docker:

![docker pull](https://img.shields.io/docker/pulls/arcblock/abtnode.svg)

\`\`\`shell
docker pull arcblock/abtnode
docker run -d -p 80:80 -p 443:443  -v <your host directory>:/data/abtnode arcblock/abtnode
\`\`\`

The data generated by the node is placed in the /data/abtnode directory in the container, and we recommend trying not to place the data in the container, keep the container stateless.

### Troubleshooting

If your container does not start as expected, you can run the command without \`-d\`:

\`\`\`shell
docker run -p 80:80 -p 443:443 -v <your host directory>:/data/abtnode arcblock/abtnode
\`\`\`

## License

Copyright 2018-2020 ArcBlock

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
`;

fs.writeFileSync(readmeFile, readmeContent);
console.log('README.md updated');
