name: 'Version Check'

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - master
jobs:
  check-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: action-version-check
        uses: arcblock/action-version-check@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
